Repository andela/ah-frontend-sparta, pull requests merged in 2019-05, with the labels that each got.

#6 #164798158 Update TravisCI to run tests
  .travis.yml
  README.md
  package-lock.json
Labels: Finished

#3 #164798156 Setting Redux In Created React Project
  .eslintrc.js
  package-lock.json
  package.json
  src/index.js
  src/reducers/authReducer.js
  src/reducers/index.js
  src/store.js
Labels: Finished

#7 #164798160 Setting up Sass css
  ignore-module.js
  jest.config.js
  package-lock.json
  package.json
  src/assets/scss/style.scss
  src/components/App.js
  webpack.config.js
Labels: Finished

#5 #165675656 Hosting Application on Heroku
  Procfile
  package-lock.json
  package.json
  server.js
Labels: Finished

#9 #164798162 Run Code Climate Coverage
  .travis.yml
  README.md
Labels: Finished

#10 User should signup
  .gitignore
  ignore-css.js
  package-lock.json
  package.json
  public/dest/style.css
  src/.DS_Store
  src/actions/signupSigninActions.js
  src/actions/types.js
  src/assets/icons/index.js
  src/assets/icons/index.scss
  src/assets/images/Hamburger_icon.svg.png
  src/assets/images/article_image.jpeg
  src/assets/images/bookmark.png
  src/assets/images/facebook.png
  src/assets/images/gmail.png
  src/assets/images/icons8-search-30.png
  src/assets/images/landing_image.jpg
  src/assets/images/login_signup.jpg
  src/assets/images/logo.png
  src/assets/images/logo2.png
  src/assets/images/search-3-32.jpg
  src/assets/images/search.svg
  src/assets/images/twitter.png
  src/assets/scss/Login.scss
  src/assets/scss/shared.scss
  src/components/App/index.js
  src/components/InputBox/InputBox.scss
  src/components/InputBox/index.js
  src/components/LandingPageWrapper.js
  src/components/LandingPageWrapper/index.js
  src/components/Login.js
  src/components/NavBar/NavBar.scss
  src/components/NavBar/index.js
  src/components/Navbar.js
  src/components/Routes.js
  src/components/SigninForm/index.js
  src/components/SignupButton/SignupButton.scss
  src/components/SignupButton/index.js
  src/components/SignupForm/index.js
  src/index.js
  src/pages/Landing/Landing.scss
  src/pages/Landing/index.js
  src/pages/Routes.js
  src/pages/Signin/index.js
  src/pages/Signup/index.js
  src/reducers/index.js
  src/reducers/signupSignupReducer.js
  src/tests/Signin.test..js
  src/tests/__snapshots__/App.test.js.snap
  src/tests/__snapshots__/Landing.test.js.snap
  src/tests/__snapshots__/Login.test.js.snap
Labels: in progress

#19 #165879303 Bug fix not allowing heroku to fully build the application
  src/components/InputBox/index.js
Labels: in progress

#26 #165911808 Integrate Coveralls for code coverage
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: Finished

#20 Enable User to signup and login to authors haven
  .eslintrc.js
  dist/config.js
  package-lock.json
  package.json
  src/actions/signupSigninActions.js
  src/actions/types.js
  src/assets/icons/icons.test.jsx
  src/assets/icons/index.jsx
  src/components/InputBox/InputBox.test.jsx
  src/components/InputBox/index.js
  src/components/InputBox/index.jsx
  src/components/LandingPageWrapper/index.js
  src/components/LandingPageWrapper/index.jsx
  src/components/NavBar/index.js
  src/components/NavBar/index.jsx
  src/components/SigninForm/SigninForm.test.jsx
  src/components/SigninForm/index.js
  src/components/SigninForm/index.jsx
  src/components/SignupButton/SIgnupButton.test.jsx
  src/components/SignupButton/index.js
  src/components/SignupButton/index.jsx
  src/components/SignupForm/SignupForm.test.jsx
  src/components/SignupForm/index.js
  src/components/SignupForm/index.jsx
  src/components/Starter.js
  src/components/StarterContainer.js
  src/data/sample_articles.js
  src/index.jsx
  src/pages/Landing/index.js
  src/pages/Landing/index.jsx
  src/pages/Routes.jsx
  src/pages/Signin/Signin.test.jsx
  src/pages/Signin/index.js
  src/pages/Signin/index.jsx
  src/pages/Signup/Signup.test.jsx
  src/pages/Signup/index.js
  src/pages/Signup/index.jsx
  src/reducers/index.js
  src/reducers/signupSignupReducer.js
  src/reducers/tests/signupSignupReducer.test.js
  src/tests/Landing.test.jsx
  src/tests/Signin.test..js
  src/tests/Starter.test.js
  src/tests/__snapshots__/App.test.js.snap
  src/tests/__snapshots__/Starter.test.js.snap
  webpack.config.js
Labels: Finished

#29 Add a .env file to codebase
  .env-sample
  .eslintrc.js
  .gitignore
  dist/config.js
  package-lock.json
  package.json
  src/actions/signupSigninActions.js
  src/helpers/axiosInstance.js
  webpack.config.js
Labels: Finished

#22 #165909011 Getting articles from an endpoint to display on the landing page
  package-lock.json
  package.json
  src/actions/articlesActions.js
  src/actions/types.js
  src/components/Articles/ArticleContainer.jsx
  src/components/Articles/DisplaySampleArticles.jsx
  src/components/Articles/DisplayTrendingArticles.jsx
  src/components/Articles/TrendingArticles.jsx
  src/components/Articles/index.jsx
  src/components/LandingPageWrapper/index.jsx
  src/data/sample_articles.js
  src/helpers/randomArticles.js
  src/pages/Landing/Landing.scss
  src/pages/Landing/index.jsx
  src/pages/Landing/tests/Landing.test.js
  src/pages/Landing/tests/__snapshots__/Landing.test.js.snap
  src/pages/Routes.jsx
  src/reducers/articlesReducer.js
  src/reducers/index.js
  src/tests/App.test.js
  src/tests/App.test.jsx
  src/tests/Landing.test.jsx
  src/tests/__snapshots__/App.test.js.snap
  src/tests/__snapshots__/App.test.jsx.snap
  src/tests/__snapshots__/Landing.test.jsx.snap
  src/tests/actions/ArticlesActions.test.js
  src/tests/components/TrendingArticles.test.jsx
  src/tests/components/__snapshots__/TrendingArticles.test.jsx.snap
  src/tests/components/__snapshots__/sampleArticles.test.jsx.snap
  src/tests/components/sampleArticles.test.jsx
  src/tests/reducers/ArticlesReducer.test.js
Labels: Asking for merge, Finished

#25 164798164 Reset password link
  .eslintrc.js
  package-lock.json
  package.json
  src/actions/resetActions/changePasswordActions.js
  src/actions/resetActions/resetPasswordActions.js
  src/actions/types.js
  src/assets/scss/Login.scss
  src/components/PasswordResetForm/index.jsx
  src/components/SigninForm/SigninForm.test.jsx
  src/components/SigninForm/__snapshots__/SigninForm.test.jsx.snap
  src/components/SigninForm/index.jsx
  src/components/resetPassword/__snapshots__/resetPassword.test.jsx.snap
  src/components/resetPassword/index.jsx
  src/components/resetPassword/resetPassword.test.jsx
  src/pages/Landing/Landing.scss
  src/pages/PasswordReset/ResetPasswordContainer.jsx
  src/pages/PasswordReset/index.jsx
  src/pages/PasswordReset/resetPassword.scss
  src/pages/Routes.jsx
  src/reducers/index.js
  src/reducers/resetReducer.js
  src/reducers/signupSignupReducer.js
  src/reducers/tests/actions/resetActions.test.jsx
  src/reducers/tests/changeActions.test.jsx
  src/reducers/tests/fixtures/moxios_mock.jsx
  src/tests/reducers/resetReducer.test.jsx
  src/utils/Notify.js
  webpack.config.js
Labels: Finished, ready for reviews

#31 #164798167 Enable users to view and edit their profiles
  package-lock.json
  package.json
  src/actions/profileActions.js
  src/actions/signupSigninActions.js
  src/actions/types.js
  src/assets/images/profilePic.jpg
  src/assets/scss/Login.scss
  src/components/EditProfileInput/EditProfileInput.test.js
  src/components/EditProfileInput/index.jsx
  src/components/EditProfileInput/profileInput.scss
  src/components/InputBox/InputBox.scss
  src/components/InputBox/__snapshots__/InputBox.test.jsx.snap
  src/components/InputBox/index.jsx
  src/components/NavBar/NavBar.test.jsx
  src/components/NavBar/index.jsx
  src/components/NavBarAccountSection/NavBarAccountSection.scss
  src/components/NavBarAccountSection/index.jsx
  src/components/ProgressBar/ProgressBar.scss
  src/components/ProgressBar/ProgressBar.test.js
  src/components/ProgressBar/index.jsx
  src/components/SigninForm/__snapshots__/SigninForm.test.jsx.snap
  src/components/SigninForm/index.jsx
  src/components/SignupButton/SignupButton.scss
  src/components/SignupButton/__snapshots__/SIgnupButton.test.jsx.snap
  src/components/SignupButton/index.jsx
  src/components/SignupForm/__snapshots__/SignupForm.test.jsx.snap
  src/components/resetPassword/__snapshots__/resetPassword.test.jsx.snap
  src/pages/EditProfile/EditProfile.scss
  src/pages/EditProfile/EditProfile.test.jsx
  src/pages/EditProfile/index.jsx
  src/pages/PasswordReset/resetPassword.scss
  src/pages/Routes.jsx
  src/pages/ViewProflle/ViewProfile.scss
  src/pages/ViewProflle/ViewProfile.test.jsx
  src/pages/ViewProflle/index.jsx
  src/reducers/index.js
  src/reducers/profileReducer.js
  src/reducers/tests/signupSignupReducer.test.js
  src/tests/actions/ProfileActionsTest.test.js
Labels: in progress

#33 #166003010 Authentication private routes
  package-lock.json
  src/actions/facebookActions.js
  src/actions/profileActions.js
  src/actions/signupSigninActions.js
  src/actions/types.js
  src/components/EditProfileInput/__snapshots__/EditProfileInput.test.js.snap
  src/components/NavBar/index.jsx
  src/components/PrivateRoute/PrivateRoute.jsx
  src/components/PrivateRoute/TestComponent.jsx
  src/components/PrivateRoute/test/TestComponent.test.jsx
  src/components/PrivateRoute/test/__snapshots__/TestComponent.test.jsx.snap
  src/components/ProgressBar/__snapshots__/ProgressBar.test.js.snap
  src/components/socialLogin/tests/FaceBookActions.test.js
  src/components/socialLogin/tests/Google.test.jsx
  src/components/socialLogin/tests/facebookReducer.test.js
  src/helpers/responseGoogle.js
  src/pages/Routes.jsx
  src/pages/ViewProflle/index.jsx
  src/reducers/facebookReducer.js
Labels: Asking for merge, Finished, ready for reviews

#32 Ft-#164798168 Creating And Getting Articles
  .eslintrc.js
  package-lock.json
  package.json
  src/actions/articlesActions.js
  src/actions/signupSigninActions.js
  src/actions/types.js
  src/assets/images/avarta.png
  src/components/Articles/ArticleContainer.jsx
  src/components/Articles/ArticleDetail.jsx
  src/components/Articles/DashboardArticles.jsx
  src/components/Articles/DeleteArticleModel.jsx
  src/components/Articles/DisplayArticles.jsx
  src/components/Articles/article.scss
  src/components/Articles/articlesIcons.jsx
  src/components/Articles/createArticles.jsx
  src/components/InputBox/__snapshots__/InputBox.test.jsx.snap
  src/components/InputBox/index.jsx
  src/components/NavBar/index.jsx
  src/components/SigninForm/__snapshots__/SigninForm.test.jsx.snap
  src/components/SignupForm/__snapshots__/SignupForm.test.jsx.snap
  src/components/SignupForm/index.jsx
  src/components/resetPassword/__snapshots__/resetPassword.test.jsx.snap
  src/helpers/axiosInstance.js
  src/helpers/handleArticleTags.js
  src/index.html
  src/pages/Articles/articles.scss
  src/pages/Articles/countries.js
  src/pages/Articles/index.jsx
  src/pages/Articles/tests/__snapshots__/createArticlePage.test.jsx.snap
  src/pages/Articles/tests/createArticlePage.test.jsx
  src/pages/Dashboard/index.jsx
  src/pages/Dashboard/tests/Dashboard.test.jsx
  src/pages/Dashboard/tests/__snapshots__/Dashboard.test.jsx.snap
  src/pages/Landing/index.jsx
  src/pages/Routes.jsx
  src/pages/singleArticle/index.jsx
  src/pages/singleArticle/tests/__snapshots__/singleArticle.test.jsx.snap
  src/pages/singleArticle/tests/singleArticle.test.jsx
  src/reducers/articlesReducer.js
  src/reducers/index.js
  src/store.js
  src/tests/__snapshots__/App.test.jsx.snap
  src/tests/actions/ArticlesActions.test.js
  src/tests/components/ArticleDetail.test.jsx
  src/tests/components/DashboardArticles.test.jsx
  src/tests/components/__snapshots__/ArticleDetail.test.jsx.snap
  src/tests/components/__snapshots__/DashboardArticles.test.jsx.snap
  src/tests/reducers/ArticlesReducer.test.js
  webpack.config.js
Labels: Finished

#35 #164798170 User Should be able to comment on articles
  src/actions/articlesActions.js
  src/actions/commentActions.js
  src/actions/index.js
  src/actions/signupSigninActions.js
  src/actions/types.js
  src/components/Articles/ArticleDetail.jsx
  src/components/Comment/Comment.scss
  src/components/Comment/Comment.test.jsx
  src/components/Comment/index.jsx
  src/components/CommentReplies/CommentReplies.scss
  src/components/CommentReplies/CommentReplies.test.jsx
  src/components/CommentReplies/index.jsx
  src/components/EditCommentDialog/EditCommentDialog.scss
  src/components/EditCommentDialog/EditCommentDialog.test.jsx
  src/components/EditCommentDialog/index.jsx
  src/components/ReplyToArticle/ReplyToArticle.test.jsx
  src/components/ReplyToArticle/index.jsx
  src/components/ReplyToComment/ReplyToComment.scss
  src/components/ReplyToComment/ReplyToComment.test.jsx
  src/components/ReplyToComment/index.jsx
  src/pages/Comments/Comments.test.jsx
  src/pages/Comments/index.jsx
  src/pages/Routes.jsx
  src/pages/singleArticle/index.jsx
  src/pages/singleArticle/tests/singleArticle.test.jsx
  src/reducers/commentsReducer.js
  src/reducers/index.js
  src/tests/actions/Articles.test.js
  src/tests/actions/commentsActions.test.js
  src/tests/actions/signupSignInActions.test.js
  src/tests/components/ArticleDetail.test.jsx
  src/tests/reducers/profileReducer.test.js
Labels: in progress

#36 #164798172 Users should be able to like and or dislike articles
  .gitignore
  package-lock.json
  src/actions/facebookActions.js
  src/actions/likeDislikeActions.js
  src/actions/tests/likeDislikeActions.test.jsx
  src/actions/tests/likeDislikeReducer.test.js
  src/actions/types.js
  src/components/Articles/ArticleDetail.jsx
  src/components/Articles/DisplayArticles.jsx
  src/components/Articles/article.scss
  src/components/Articles/articlesIcons.jsx
  src/components/Comment/index.jsx
  src/components/CommentReplies/__snapshots__/CommentReplies.test.jsx.snap
  src/components/EditCommentDialog/__snapshots__/EditCommentDialog.test.jsx.snap
  src/components/EditCommentDialog/index.jsx
  src/components/ReplyToArticle/__snapshots__/ReplyToArticle.test.jsx.snap
  src/components/ReplyToComment/__snapshots__/ReplyToComment.test.jsx.snap
  src/helpers/responseGoogle.js
  src/pages/Comments/__snapshots__/Comments.test.jsx.snap
  src/pages/Routes.jsx
  src/pages/singleArticle/index.jsx
  src/pages/singleArticle/tests/__snapshots__/singleArticle.test.jsx.snap
  src/pages/singleArticle/tests/singleArticle.test.jsx
  src/reducers/index.js
  src/reducers/likeDislikeReducer.js
  src/setupTest.js
  src/tests/components/__snapshots__/ArticleDetail.test.jsx.snap
Labels: Asking for merge, Finished, ready for reviews

#41 #166193863 Custom 404 page and fix to dashboard not protected
  src/components/Custom404/Error.jsx
  src/components/Custom404/ErrorStyles.css
  src/components/Custom404/tests/Error.test.jsx
  src/components/Custom404/tests/__snapshots__/Error.test.jsx.snap
  src/pages/Routes.jsx
Labels: Finished, ready for reviews

#40 164798169 Rate Articles
  package-lock.json
  package.json
  src/actions/articlesActions.js
  src/actions/ratingActions.jsx
  src/actions/types.js
  src/components/Articles/ArticleDetail.jsx
  src/components/Articles/DisplayArticles.jsx
  src/components/Articles/article.scss
  src/components/Rating/index.js
  src/components/Ratings/index.jsx
  src/pages/Dashboard/Dashboard.scss
  src/pages/Dashboard/index.jsx
  src/pages/Landing/Landing.scss
  src/pages/Landing/index.jsx
  src/pages/Ratings/index.jsx
  src/pages/Ratings/tests/RatingAction.test.js
  src/pages/Ratings/tests/RatingContainer.test.jsx
  src/pages/singleArticle/index.jsx
  src/pages/singleArticle/tests/singleArticle.test.jsx
  src/reducers/index.js
  src/reducers/ratingsReducers.jsx
  src/tests/__snapshots__/App.test.jsx.snap
  src/tests/components/__snapshots__/DashboardArticles.test.jsx.snap
  src/tests/reducers/ratingsReducer.test.jsx
Labels: in progress

#43 #164798187 User Should view their reading stats
  package-lock.json
  src/actions/articlesActions.js
  src/components/Articles/DashboardArticles.jsx
  src/components/Articles/article.scss
  src/components/Comment/index.jsx
  src/components/CommentReplies/index.jsx
  src/components/EditCommentDialog/index.jsx
  src/components/NavBar/index.jsx
  src/pages/ReadingStats/ReadingStats.test.jsx
  src/pages/ReadingStats/index.jsx
  src/pages/Routes.jsx
  src/pages/singleArticle/index.jsx
  src/pages/singleArticle/tests/singleArticle.test.jsx
  src/reducers/articlesReducer.js
  src/tests/actions/Articles.test.js
  src/tests/actions/ArticlesActions.test.js
  src/tests/reducers/ArticlesReducer.test.js
Labels: Finished
